package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
	"time"
	// swaggerFiles "github.com/swaggo/files"
	// "github.com/swaggo/gin-swagger"
	// _ "./docs" // docs is generated by Swag CLI, you have to import it.

	"sinistra/deltatre/frontend/controllers"
)

func main() {

	wordController := controllers.WordController{}

	router := gin.New()
	router.Use(gin.LoggerWithFormatter(func(param gin.LogFormatterParams) string {
		// custom format
		return fmt.Sprintf("%s |%s|[%s]|%s|%s|%d|%s|%s|%s\n",
			param.TimeStamp.Format(time.RFC3339),
			param.Method,
			param.ClientIP,
			param.Path,
			param.Request.Proto,
			param.StatusCode,
			param.Latency,
			param.Request.UserAgent(),
			param.ErrorMessage,
		)
	}))

	// Recovery middleware recovers from any panics and writes a 500 if there was one.
	router.Use(gin.Recovery())

	// url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	// router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	v1 := router.Group("/api/v1")
	{
		v1.GET("/search", wordController.GetWord)
		// v1.POST("/add", addTodo)
		// v1.GET("/", fetchAllTodo)
		// v1.GET("/:id", fetchSingleTodo)
		// v1.PUT("/:id", updateTodo)
		// v1.DELETE("/:id", deleteTodo)
	}

	// healthcheck
	router.GET("/ping", func(ctx *gin.Context) {
		ctx.JSON(http.StatusOK, gin.H{
			"message": "pong",
		})
	})

	// Listen and serve on 0.0.0.0:8000
	router.Run(":8000")
}
